[package]
name = "game-boy-inator"
version = "0.1.0"
edition = "2021"

[lib]
name = "game_boy_hardware"
path = "src/game_boy_hardware/lib.rs"

[[bin]]
name = "game-boy-inator"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.35"
features = ["bundled", "static-link"]

[patch.crates-io]
cmake = {git = 'https://github.com/alexcrichton/cmake-rs', rev = 'dca4a9df71df40eeb57b974703d745607b168d9f'}
