name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build
      run: cargo build --release --verbose

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build
      run: cargo build --release --verbose

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build
      run: cargo build --release --verbose
      
  test-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Run Tests
      run: cargo test --release --verbose
      
  test-mac:
    needs: build-mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Run Tests
      run: cargo test --release --verbose
      
  test-windows:
    needs: build-windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Run Tests
      run: cargo test --release --verbose
