name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build static-link
      id: static
      run: cargo build --release --verbose --features "sdl2/static-link"
    - name: Build dynamic-link
      id: dynamic
      if: ${{static.status == 'failure'}}
      run: cargo build --release --verbose
    - name: Run Tests
      if: ${{static.status != 'failure' || dynamic.status != 'failure'}}
      run: cargo test --release --verbose

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build static-link
      id: static
      run: cargo build --release --verbose --features "sdl2/static-link"
    - name: Build dynamic-link
      id: dynamic
      if: ${{static.status == 'failure'}}
      run: cargo build --release --verbose
    - name: Run Tests
      if: ${{static.status != 'failure' || dynamic.status != 'failure'}}
      run: cargo test --release --verbose

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update
    - name: Build static-link
      id: static
      run: cargo build --release --verbose --features "sdl2/static-link"
    - name: Build dynamic-link
      id: dynamic
      if: ${{static.status == 'failure'}}
      run: cargo build --release --verbose
    - name: Run Tests
      if: ${{static.status != 'failure' || dynamic.status != 'failure'}}
      run: cargo test --release --verbose
